### ISSUE TITLE
项目搭建、开发规范约定

### ISSUE THREAD

**Issue by Anonymity94** [nice-people-frontend-community/nice-leetcode#4]
## 技术栈：
- Vue3
- Vite
- TS

## 功能要求：
1. 完成项目搭建
2. 开发规范约定：eslint、Prettier、git message提交约束等
3. 目录调整，给出设计依据即可
4. 初始化 4 个空白页面，可以通过输入 URI 正常跳转到页面中：
 日报页面、周报页面、总榜页面、头等舱页面

## 文档输出：
1. 简要的搭建过程说明
2. cli 中用到了哪些 npm 包，都是哪些作用
5. 提供项目启动说明，提供参与贡献说明

## 相关面试题

- 如何进行技术选型？
- 前端架构中通常会考虑哪些要素？

**Comment by Sneaken** [comment]
👋

**Comment by karasHou** [comment]
来了
