### ISSUE TITLE
头等舱航班页面

### ISSUE THREAD

**Issue by Anonymity94** [nice-people-frontend-community/nice-leetcode#7]
## 功能点
- 提示信息（公共组件）
- 月份选择器
- 清除缓存按钮
- 人员名单列表

## 原始代码
https://github.com/nice-people-frontend-community/nice-leetcode/blob/master/docs/first-class.html

## 页面预览
https://nice-people-frontend-community.github.io/nice-leetcode/docs/first-class

![image](https://user-images.githubusercontent.com/13148447/174424142-828d46d7-0860-4667-a1c8-85ff160ccabc.png)

**Comment by karasHou** [comment]
🙋🏻‍♀️
