### ISSUE TITLE
总榜页面

### ISSUE THREAD

**Issue by Anonymity94** [nice-people-frontend-community/nice-leetcode#8]
## 功能点
- 用户名称
- 用户等级展示：太阳、月亮、星星
- 坚持周数展示（不同的月份需要有不同的底色，可以参考语雀中的总榜表格）

## 原始代码
https://github.com/nice-people-frontend-community/nice-leetcode/blob/master/docs/ranking.html

## 页面预览

https://nice-people-frontend-community.github.io/nice-leetcode/docs/ranking

![image](https://user-images.githubusercontent.com/13148447/174424205-a1995c97-c138-47fb-b06d-8d29593125fc.png)

**Comment by s-xiaoxiao** [comment]
- [ ] 开发总榜页面
